### ISSUE TITLE
line 99 nil value 

### ISSUE THREAD

**Issue by Ninjaskill** [tdk1069/Lazy#1]
Lazy addon works for awhile then after awhile I'm getting
Lua runetimeerror: Lazy/lazy.lua: 00: attempt to index a nil value.

**Comment by Yagamyi** [comment]
Have the same error message and then the helper bot stops weapon skills and stops functioning altogether.

**Comment by tdk1069** [comment]
Hi.. unfortunately I stopped playing XI years ago so have not updated this in a very long long time. I honestly am surprised it still works at all with the changes made and doesn't just crash. I don't even have XI installed let alone a subscription to test / debug.. sorry !

**Comment by Yagamyi** [comment]
Sorry to hear that! You should come back in XI, its gotten so much more fun! 

I must also say thank you for your hard work and dedication put into making this program, while it can be picky at times, it does work successfully most times.  

So you coded it very well and it held true to the test of time! I hope they make another beautiful game like ffxi was and you can enjoy and make more program creations.

Merry christmas & have a great new year! ; )

**Comment by tdk1069** [comment]
That's the xi community I remember :) you have a great holiday too.

I am curious if you have the time, do you know what the EU scene is like now a days ? I remember it being very lonely in eu prime hours making things hard to get anything done? 

I admit it... I am having nostalgia feelings ;)
