### ISSUE TITLE
It's broken

### ISSUE THREAD

**Issue by Mercurian** [tdk1069/Lazy#4]
I don't know what or when, but I tried using this until the API for EF is fixed and while it will function, line 99 is broken in some way and it stops working after a couple kills.

**Comment by gwbischof** [comment]
It's working well for me, I just had to change some of the settings. I'll push my changes to my fork.

**Comment by gwbischof** [comment]
Ohh, I got the error on line 99. Ill try to fix it.

**Comment by gwbischof** [comment]
It looks like there is a race condition here:
```
154     if windower.ffxi.get_player().status == 1 then
155         TurnToTarget()
156         Check_Distance()
```

I think the solution is to add the `pcall` here:

```
142     if isBusy < 1 then
143         pcall(Combat)
144     else
```

**Comment by gwbischof** [comment]
I think my PR fixes it
