### ISSUE TITLE
not engaging mobs

### ISSUE THREAD

**Issue by sixtynerf** [tdk1069/Lazy#6]
not sure if its an issue but it does not seems to auto engage mob? does thr addon actually does that? if a mob is close to 3 yalms and its in the target list, is it suppose to auto ennage and attack?

**Comment by johan-sorman** [comment]
> not sure if its an issue but it does not seems to auto engage mob? does thr addon actually does that? if a mob is close to 3 yalms and its in the target list, is it suppose to auto ennage and attack?

 The orginal author doesn't play the game so I wouldn't expect any answer here.
